// <auto-generated />
namespace ML_TP034533.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class addCustomerModel : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addCustomerModel));
        
        string IMigrationMetadata.Id
        {
            get { return "201804122037138_addCustomerModel"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
